#if !canImport(ObjectiveC)
import XCTest

extension EventTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EventTests = [
        ("testAppend", testAppend),
        ("testApply", testApply),
        ("testCatOptionals", testCatOptionals),
        ("testCombine", testCombine),
        ("testConcat", testConcat),
        ("testCount", testCount),
        ("testFilter", testFilter),
        ("testMap", testMap),
        ("testMapOptional", testMapOptional),
        ("testMerge", testMerge),
        ("testReduce", testReduce),
        ("testSampleOn", testSampleOn),
        ("testWithLast", testWithLast),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(EventTests.__allTests__EventTests),
    ]
}
#endif
