os:
  - linux
env:
language: generic
sudo: required
dist: trusty
install:
  - if [ $TRAVIS_OS_NAME = linux ]; then
      eval "$(https://swiftenv.fuller.li/install.sh)";
      swiftenv rehash;
    fi
script:
  - swift test
