#if !canImport(ObjectiveC)
import XCTest

extension ValidationNearSemiringTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ValidationNearSemiringTests = [
        ("testInvalidData", testInvalidData),
        ("testValidData", testValidData),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ValidationNearSemiringTests.__allTests__ValidationNearSemiringTests),
    ]
}
#endif
