import XCTest
@testable import PreludeTests

XCTMain([
  testCase(EquatableTests.allTests),
  testCase(ArrayTests.allTests),
  testCase(FreeNearSemiringTests.allTests),
  testCase(FunctionTests.allTests),
  testCase(KeyPathTests.allTests),
  testCase(MonoidTests.allTests),
  testCase(OptionalTests.allTests),
  testCase(ParallelTests.allTests),
  testCase(SemigroupTests.allTests),
  testCase(SequenceTests.allTests),
  testCase(StringTests.allTests),
  testCase(StrongTests.allTests),
  testCase(TupleTests.allTests),
  testCase(UnitTests.allTests),
  testCase(ChoiceTests.allTests),
  testCase(EitherTests.allTests),
  testCase(NestedTests.allTests),
  testCase(StateTests.allTests),
  testCase(OpticsTests.allTests),
  testCase(ValidationSemigroupTests.allTests),
  testCase(ReaderTests.allTests),
  testCase(ValidationNearSemiringTests.allTests),
  testCase(NonEmptyTests.allTests),
  testCase(TupleTests.allTests),
  testCase(EventTests.allTests),
])
