#if !canImport(ObjectiveC)
import XCTest

extension EitherTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EitherTests = [
        ("testAlt", testAlt),
        ("testAppend", testAppend),
        ("testApply", testApply),
        ("testEither", testEither),
        ("testIsLeft", testIsLeft),
        ("testIsRight", testIsRight),
        ("testLeft", testLeft),
        ("testMap", testMap),
        ("testPure", testPure),
        ("testRight", testRight),
        ("testUnwrap", testUnwrap),
        ("testWrap", testWrap),
    ]
}

extension NestedTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NestedTests = [
        ("testNested", testNested),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(EitherTests.__allTests__EitherTests),
        testCase(NestedTests.__allTests__NestedTests),
    ]
}
#endif
