#if !canImport(ObjectiveC)
import XCTest

extension OpticsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OpticsTests = [
        ("testAddOver", testAddOver),
        ("testAppendOver", testAppendOver),
        ("testChoicePrisms", testChoicePrisms),
        ("testConjOver", testConjOver),
        ("testDisjOver", testDisjOver),
        ("testDivOver", testDivOver),
        ("testElem", testElem),
        ("testGetters", testGetters),
        ("testIx", testIx),
        ("testKey", testKey),
        ("testLots", testLots),
        ("testMulOver", testMulOver),
        ("testOver", testOver),
        ("testSet", testSet),
        ("testStrongPrisms", testStrongPrisms),
        ("testSubOver", testSubOver),
        ("testTraversed", testTraversed),
        ("testViewOn", testViewOn),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(OpticsTests.__allTests__OpticsTests),
    ]
}
#endif
