#if !canImport(ObjectiveC)
import XCTest

extension ValidationSemigroupTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ValidationSemigroupTests = [
        ("testInvalidData", testInvalidData),
        ("testValidData", testValidData),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ValidationSemigroupTests.__allTests__ValidationSemigroupTests),
    ]
}
#endif
