#if !canImport(ObjectiveC)
import XCTest

extension TupleTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TupleTests = [
        ("testTuples", testTuples),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(TupleTests.__allTests__TupleTests),
    ]
}
#endif
